- name: upgrade de todos pacotes do S.O
  yum:
    name: '*'
- name: install git
  yum:
    name: git
    state: latest
- name: instalação do Maven
  maven_major: 3
  maven_version: 3.3.9
  maven_home_parent_directory: /opt
  maven_env_file: "/etc/profile.d/maven.sh"