---

- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhosts: "db01"
    - dbname:  "notes"
    - dbusername: "notesapp"
    - dbpassword: "devops"
  tasks:
    - name: config host lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
         -  192.168.1.2 control-node
         -  192.168.1.3 app01
         -  192.168.1.4 db01
    - name: Adicionar usuarioa de app
      user:
       name: app
       comment: usuario 
       uid: 500
    - name: Instalação do Maven
      yum:
       name: maven
       state: latest
    - name: Instalação do Java
      yum:
       name: java-1.8.0-openjdk
       state: latest
    - name: Criação do diretório de app
      file: 
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: install git
      yum:
        name: git
        state: latest
    - name: Clone do repositorio Notes - app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacote da aplicação
      command: mvn -f /opt/notes/pom.xml package
      become_user: app    
    - name: Registrar versão atual do pacote
      shell:
       cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec
       chdir: /opt/notes
      register: app_version
    - name: Configurar serviço do Systemd
      template:
       src: etc/systemd/system/notes.service
       dest: /etc/systemd/system/notes.service
       notify: reload daemon
    - name: Iniciar serviço Notes
      service:
       name: notes 
       state: restarted
  roles:
    - config-default-so
  handlers:
    - name: reload app  
      systemd:
       state: restarted
       daemon_reload: yes
       name: 'notes'
    - name: relaod daemon
      systemd:  
       daemon_reexec: yes
