---
- name: Configurar Servidor de aplicação java
  hosts: app01
  
  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devops"
  tasks:
   - name: configurar hosts labs ansible
     lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
     with_items:
         -  192.168.1.2 control-node
         -  192.168.1.3 app01
         -  192.168.1.4 db01
   - name: Adicionar usuario de app01
     user:
       name: app0
       comment: usuario de aplicação
       uid: 500
   - name: Instalação do Maven
     yum:
       name: maven 
       state: latest
   - name: Instalação do java
     yum:
       name: java-1.8.0-openjdk
       state: latest
   - name: Criação do diretorio de app
     file: 
       path: /opt/notes
       state: directory
       owner: app
       group: app
   - name: Clone do repositorio notes - app
     git:
       repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
       dest: /opt/notes
       clone: yes
       force: yes    
   - name: configurar arquivo de propriedades para camada de banco de dados
     template:
       src: application.properties
       dest: /opt/notes/src/main/resources/application.properties
   - name: Gerar pacote da aplicação
     command: mvn -f /opt/notes/pom.xml package
     bacome_user: app
   - name: Registrar versão atual do pacote
     shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}'
        chdir: /opt/notes/
     register: app_version
   - name: Configurar serviço do Systemd
     template:
       src: etc/systemd/system/notes.service
       notify: reload deamon
   - name: Iniciar o serviço notes
     service:
       name: notes
       state: restarted
  roles:
    - config-default-so
  handlers:
    - name:  reload app
      systemd:
          state: restarted
          daemon_reload: yes
          name: 'notes'
    - name: reload daemon_reload
      systemd:
      daemon_reexec: yes